---
roles:
  - name: db-pull
    src: https://github.com/le-phare/ansible-db-pull

  - name: lephare.ansible-deploy
    src: https://github.com/le-phare/ansible-deploy

collections:
  - name: community.general
    source: https://galaxy.ansible.com
