- name: LEPHARE - Check for cachetool.phar
  stat: path={{ lephare_cachetool_path }}
  register: cachetool_file

- name: LEPHARE - Run cachetool self-update
  shell: "{{ lephare_cachetool_path }} self-update"
  when: cachetool_file.stat.exists and lephare_cachetool_self_update
  register: cachetool_self_update_result
  changed_when: cachetool_self_update_result.stderr

- name: LEPHARE - Install cachetool
  get_url: url=http://gordalina.github.io/cachetool/downloads/cachetool.phar dest={{ lephare_cachetool_path }} mode=0755 validate_certs=no force=no

- name: LEPHARE - Run cachetool opcache:reset
  shell: chdir={{ansistrano_release_path.stdout}}
    {{ symfony_php_path }} {{ lephare_cachetool_path }} opcache:reset --web --web-path={{ ansistrano_deploy_to }}/current/web --web-url=http://{{ inventory_hostname }}
  when: cachetool_file.stat.exists and lephare_cachetool_opcache_reset
  retries: 10
  delay: 30
  register: cachetool_opcache_result
  until: cachetool_opcache_result.rc == 0

- name: LEPHARE - Run cachetool apcu:cache:clear
  shell: chdir={{ansistrano_release_path.stdout}}
    {{ symfony_php_path }} {{ lephare_cachetool_path }} apcu:cache:clear --web --web-path={{ ansistrano_deploy_to }}/current/web --web-url=http://{{ inventory_hostname }}
  when: cachetool_file.stat.exists and lephare_cachetool_apcu_clear
  retries: 10
  delay: 30
  register: cachetool_apcu_result
  until: cachetool_apcu_result.rc == 0
